title: Biennial International Congress on Mental Health 2024
url: https://www.bicomh.com
favicon: /images/Logos/BICOMH_Logo_2.png
colors:
  primary-color: "#3c53a4"
  secondary-color: "#f6d00c"
  media-colors:
    - title: media-color-one
      color: "#f6d00c"
    - title: media-color-two
      color: "#f6d00c"
    - title: media-color-three
      color: "#3c53a4"
    - title: media-color-four
      color: "#3c53a4"
    - title: media-color-five
      color: "#3c53a4"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d3ul7qynb0xzrt.amplifyapp.com
prod: https://master.d3ci0atgo6q4xf.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
